### PR TITLE
Remaining api calls

### PR DESCRIPTION
**Pull request by zenhack**
This adds the power management API, borrowed directly from HIL.

There's also a decent  chunk of refactoring in the tests; a lot of the stuff I'd written for TestViewConsole was more generally applicable, and along the way I realized I'd written a few helpers that we should be using in places we weren't.

### CODE REVIEW

**Comment by naved001** [comment]
This mostly looks fine but I decided to actually run and test it but I couldn't get a token it returned a 404 instead. I probably overlooked that when reviewing #2. This is what I did to get my token after registering my node:

`curl --user admin:admin-token -i -X POST -H "Content-Type: application/json" http://localhost:8080/node/node1/token`

Also, I could re-register the same node again and again, and it returned 200 which doesn't feel right.

**Comment by zenhack** [comment]
Quoting Naved Ansari (2017-12-20 16:45:58)

>    This mostly looks fine but I decided to actually run and test it but I
>    couldn't get a token it returned a 404 instead. I probably overlooked
>    that when reviewing [1]#2. This is what I did to get my token after
>    registering my node:
>
>    curl --user admin:admin-token -i -X POST -H "Content-Type:
>    application/json" http://localhost:8080/node/node1/token


It works without the Content-Type header on my end, and otherwise that's
what should happen. The only other bit that's different is /token
instead of /console-endpoints, which I remember you specifically calling
out as having been missed during review.

>    Also, I could re-register the same node again and again, and it
>    returned 200 which doesn't feel right.

Yeah, that's to spec; you can update the connection info for the node
that way. I don't feel strongly about this; if you think it would be
better to require an explicit delete first I'm fine changing it.

**Comment by naved001** [comment]
> It works without the Content-Type header on my end, and otherwise that's what should happen.

Cool, this works.

> Yeah, that's to spec; you can update the connection info for the node that way. I don't feel strongly about this; if you think it would be better to require an explicit delete first I'm fine changing it.

The current behavior in HIL is to raise a [Duplicate Error](https://github.com/CCI-MOC/hil/blob/master/hil/api.py#L232) rather than silently replacing the details. This is useful in cases where people accidentally use the same name when registering a new node (e.g., typos like dell-1 vs dell-11).

Having an explicit delete would be better imo.

**Comment by naved001** [comment]
Tested the power off and power cycle calls and those work fine. Few things to note though:

1. I added some more characters to the end of my token and it still worked. 
```
[naved001@rhel-tgt-base ~]$ curl -i -X POST -H "Content-Type: application/json" -d '{"force": false}' http://localhost:8080/node/node1/power_off?token=04fe3d742e0ba2fd762193820a143fce
HTTP/1.1 200 OK
Content-Length: 0

[naved001@rhel-tgt-base ~]$ curl -i -X POST -H "Content-Type: application/json" -d '{"force": false}' http://localhost:8080/node/node1/power_off?token=04fe3d742e0ba2fd762193820a143fceGARBAGE
HTTP/1.1 200 OK
Date: Thu, 21 Dec 2017 16:29:49 GMT
Content-Length: 0
```

2. Why does a token of length one causes 500 instead of 401?
```
[naved001@rhel-tgt-base ~]$ curl -i -X POST -H "Content-Type: application/json" -d '{"force": false}' http://localhost:8080/node/node1/power_off?token=1
HTTP/1.1 500 Internal Server Error
Content-Length: 0

[naved001@rhel-tgt-base ~]$ curl -i -X POST -H "Content-Type: application/json" -d '{"force": false}' http://localhost:8080/node/node1/power_off?token=12
HTTP/1.1 401 Unauthorized
Content-Length: 0
```

Something to do with how you are getting the token from the URL?

3. Are you checking the request bodies to be of the right type? Because all of these return 200.

```
[naved001@rhel-tgt-base ~]$ curl -i -X POST -H "Content-Type: application/json" -d '{"force": boogers}' http://localhost:8080/node/node1/power_off?token=04fe3d742e0ba2fd762193820a143fce
HTTP/1.1 200 OK
Content-Length: 0

[naved001@rhel-tgt-base ~]$ curl -i -X POST -H "Content-Type: application/json" -d '{"force": boogers, "asdasd": qweqwe}' http://localhost:8080/node/node1/power_off?token=04fe3d742e0ba2fd762193820a143fce
HTTP/1.1 200 OK
Content-Length: 0

[naved001@rhel-tgt-base ~]$ curl -i -X POST -H "Content-Type: application/json" -d '{}' http://localhost:8080/node/node1/power_off?token=04fe3d742e0ba2fd762193820a143fce
HTTP/1.1 200 OK
Content-Length: 0

[naved001@rhel-tgt-base ~]$ curl -i -X POST http://localhost:8080/node/node1/power_off?token=04fe3d742e0ba2fd762193820a143fce
HTTP/1.1 200 OK
Content-Length: 0

```

4. Setting the bootdev worked for most of the cases, except if I send it 2 `bootdev`s in the body.

```
[naved001@rhel-tgt-base ~]$ curl -i -X PUT -H "Content-Type: application/json" -d '{"bootdev": "disk", "bootdev": "pxe"}' http://localhost:8080/node/node1/boot_device?token=04fe3d742e0ba2fd762193820a143fce
HTTP/1.1 200 OK
Date: Thu, 21 Dec 2017 16:42:14 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8

[naved001@rhel-tgt-base ~]$ curl -i -X PUT -H "Content-Type: application/json" -d '{"bootdev": "disk", "bootdev": "invalid"}' http://localhost:8080/node/node1/boot_device?token=04fe3d742e0ba2fd762193820a143fce
HTTP/1.1 400 Bad Request
Date: Thu, 21 Dec 2017 16:42:23 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8
```

I would debug this myself and look into the code, but I am still in the early stages of learning Go. Perhaps I'll learn some more over the Christmas break and be a changed man next year.

**Comment by zenhack** [comment]
I just pushed a commit that should fix 1 & 2.

re 3: it currently doesn't look at the body for power_off, since it doesn't actually take any parameters. Maybe we should check that it's empty, but I don't feel strongly.

re 4: having two of the same key in a JSON object is invalid, so that's working as expected.

**Comment by zenhack** [comment]
Just pushed another patch that disallows updating without deleting first. Per the commit message, I don't have time to test it just now, but it's a simple enough thing I expect it will work.

**Comment by naved001** [comment]
> re 3: it currently doesn't look at the body for power_off, since it doesn't actually take any parameters. Maybe we should check that it's empty, but I don't feel strongly.

right, that was a mistake on my part, I meant to check power_cycle which does respond with 400 if the body is malformed. So I am happy with that. and no need to check the body, we can just ignore it.

> re 4: having two of the same key in a JSON object is invalid, so that's working as expected.

In the first request of 4, I sent two valid keys and it responds with a 200.
```
[naved001@rhel-tgt-base ~]$ curl -i -X PUT -H "Content-Type: application/json" -d '{"bootdev": "disk", "bootdev": "pxe"}' http://localhost:8080/node/node1/boot_device?token=ecf4a66c4f7595e9452cbffeff452ef4
HTTP/1.1 200 OK
Date: Thu, 21 Dec 2017 20:15:01 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8

```
That's what I wanted to point at. I don't know what the bootdevice is set to now.

**Comment by zenhack** [comment]
We're shelling out to the json package to parse the bodies:

https://golang.org/pkg/encoding/json/#Unmarshal

Which is perhaps more lienient that is ideal. I'd hazard a guess that the last one takes precedence, and it's just not keeping track of what fields it's set already.

**Pull request merged**
